import { StyleSheet, Dimensions} from "react-native";
const { width, height} = Dimensions.get("window");

const styles = StyleSheet.create({
    scrollContainer: {
        paddingTop: 20,
        paddingBottom: 20,
        backgroundColor: "#fff",
        alignItems: "center",
    },
    backgroundImages: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        zIndex: -1,
      },
      vector3Image: {
        top: '0%',
        width: '100%',
        height: 750,
        resizeMode: 'cover',
      },
      rectangle105Image: {
        width: '100%',
        height: 600,
        resizeMode: 'cover',
        position: 'absolute',
        top: '60%',
      },
    container: {
        paddingTop: 0,
        paddingHorizontal: 20,
        width: "100%",
        marginBottom: 20,
    },
    header: {
        width: "30%",
        height: 50,
        flexDirection: "row",
        alignItems: "center",
        paddingHorizontal: 20,
        backgroundColor: "#f8f8f8",
        elevation: 2,
        marginBottom: 20,
    },
    backButton: {
        padding: 0,
    },
    backButtonText: {
        fontSize: 50,
        color: "black",
        fontWeight: "bold",
        marginTop: -20,
    },
    roundedBox: {
        width: width - 60,
        height: height/3,
        backgroundColor: "white",
        borderColor: '#BAE2FF',
        borderWidth: 3,
        borderTopRightRadius: 120,
        borderRadius: 15,
        justifyContent: "flex-start",
        alignItems: "center",
        shadowColor: "#000",
        shadowOffset: {width: 0, height: 2},
        shadowOpacity: 0.3,
        shadowRadius: 4,
        elevation: 5,
        marginBottom: 10,
        paddingHorizontal: 30,
    },
    circleContainer: {
        position: "absolute",
        top: 0,
        right: 0,
        flexDirection: "column",
        justifyContent: "space-between",
        alignItems: "flex-end",
        height: 100,
    },
    circle1: {
        marginRight: 80,
        marginTop: -15,
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: "#C0DAEC",
        marginBottom: 5,
        justifyContent: "center",
        alignItems: "center",
    },
    circle2: {
            marginRight: 30,
            marginTop: -30,
            width: 40,
            height: 40,
            borderRadius: 20,
            backgroundColor: "#C0DAEC",
            marginBottom: 5,
            justifyContent: "center",
            alignItems: "center",
    },
    circle3: {
            marginRight: -10,
            marginTop: 0,
            width: 40,
            height: 40,
            borderRadius: 20,
            backgroundColor: "#C0DAEC",
            marginBottom: 5,
            justifyContent: "center",
            alignItems: "center",
    },
    circle4: {
        marginRight: -20,
        marginTop: 10,
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: "#C0DAEC",
        marginBottom: 5,
        justifyContent: "center",
        alignItems: "center",
    },
    boxText: {
        top: 70,
        color: "black",
        fontWeight: "bold",
    },
    titleContainer: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        marginBottom: 20,
        width: "100%",
        paddingHorizontal: 10,
    },
    title: {
        fontSize: 24,
        fontWeight: "bold",
    },
    liveButton: {
        paddingTop: 10,
        paddingBottom: 10,
        paddingHorizontal: 20,
        backgroundColor: "red",
        borderRadius: 5,
    },
    liveButtonText: {
        color: "white",
        fontWeight: "bold",
    },
    billIdAndStatus: {
        paddingHorizontal: 10,
        marginTop: -10,
        paddingBottom: 20,
    },
    id: {
        fontSize: 20,
        fontWeight: "bold",
        paddingBottom: 20,
    },
    statusBox: {
        paddingHorizontal: 10,
        width: 80,
        height: 25,
        borderRadius: 15,
        backgroundColor: "#FEEAD3",
        marginBottom: 5,
        shadowColor: "#000",
        shadowOffset: {width: 0, height: 2},
        shadowOpacity: 0.3,
        shadowRadius: 4,
    },
    status: {
        paddingTop: 3,
        color: "black",
        fontWeight: "bold",
    },
    bookmarkIcon: {
        position: "absolute",
        top: 10,
        left: -width/3 - 15,

    },
    simplifyButton: {
        marginTop: height/5,
        marginLeft: width/2.5,
        paddingTop: 10,
        paddingBottom: 10,
        paddingHorizontal: 15,
        backgroundColor: "#C0DAEC",
        borderRadius: 20,
    },
    simplifyButtonText: {
       color: "#0064AE",
       fontWeight: "bold",
    },
    expertTitleText: {
        width: "83%",
        marginTop: 30,
        fontSize: 40,
        color: "black",
        fontWeight: "bold",
    },
    dropDown: {
        marginTop: 30,
        width: "80%",
        height: 50,
        flexDirection: "row",
        alignItems: "center",
        paddingHorizontal: 20,
        backgroundColor: "#f8f8f8",
        elevation: 2,
        marginBottom: 0,
    },
    dropdownContent: {
        width: "81%",
        borderTopWidth: 0,
        borderWidth: 3,
        borderColor: "#ddd",
        backgroundColor: "#ffffff",
        padding: 10,
    },
    modalOverlay: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: 'rgba(0,0,0,0.5)',
    },
    modalContainer: {
        marginTop: height/8,
        marginLeft: -width/10,
        width: '65%',
        padding: 20,
        backgroundColor: 'white',
        borderRadius: 10,
        alignItems: 'stretch',
    },
    item: {
        fontSize: 18,
        padding: 10,
        textAlign: 'left',
    },
    divider: {
        height: 1,
        backgroundColor: '#dcdcdc',
        marginHorizontal: 20,
    },
    simplifiedBar: {
        marginTop: 30,
        padding: 10,
        backgroundColor: "white",
        borderRadius: 10,
        alignItems: "center",
        justifyContent: "center",
    },
    sliderLabels: {
        flexDirection: "row",
        justifyContent: "space-between",
        width: 250,
        marginTop: 5,
    },
    label: {
        fontSize: 14,
        color: "#666",
    },
    activeLabel: {
        fontSize: 14,
        fontWeight: "bold",
        color: "#000",
    },

});

export default styles;