import { StyleSheet, Dimensions} from "react-native";
const { width, height} = Dimensions.get("window");
import globalStyles from '../../global_styles'

const styles = StyleSheet.create({
    scrollContainer: {
        paddingTop: 20,
        paddingBottom: 20,
        backgroundColor: globalStyles.colors.white,
        alignItems: "center",
    },
    backgroundImages: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        zIndex: -1,
      },
      vector3Image: {
        top: '0%',
        width: '100%',
        height: 750,
        resizeMode: 'cover',
      },
      rectangle105Image: {
        width: '100%',
        height: 600,
        resizeMode: 'cover',
        position: 'absolute',
        top: '60%',
      },
    container: {
        paddingTop: 0,
        paddingHorizontal: 20,
        width: "100%",
        marginBottom: 20,
    },
    header: {
        width: "30%",
        height: 50,
        flexDirection: "row",
        alignItems: "center",
        paddingHorizontal: 20,
        backgroundColor: globalStyles.colors.white,
        marginBottom: 20,
    },
    backButton: {
        padding: 0,
    },
    backButtonText: {
        fontSize: 50,
        color: globalStyles.colors.black,
        fontWeight: "bold",
        marginTop: -20,
    },
    roundedBox: {
        width: width - 60,
        height: height/2.5,
        backgroundColor: globalStyles.colors.white,
        borderColor: globalStyles.colors.blue1,
        borderWidth: 3,
        borderTopRightRadius: 120,
        borderRadius: 15,
        justifyContent: "flex-start",
        alignItems: "center",
        shadowColor: "#000",
        shadowOffset: {width: 0, height: 2},
        shadowOpacity: 0.3,
        shadowRadius: 4,
        elevation: 5,
        marginBottom: 10,
        paddingHorizontal: 30,
        flex: 1,
    },
    circleContainer: {
        position: "absolute",
        top: 0,
        right: 0,
        flexDirection: "column",
        justifyContent: "space-between",
        alignItems: "flex-end",
        height: 100,
    },
    circle1: {
        marginRight: 80,
        marginTop: -15,
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: globalStyles.colors.buttonBlue1,
        marginBottom: 5,
        justifyContent: "center",
        alignItems: "center",
    },
    circle2: {
            marginRight: 30,
            marginTop: -30,
            width: 40,
            height: 40,
            borderRadius: 20,
            backgroundColor: globalStyles.colors.buttonBlue1,
            marginBottom: 5,
            justifyContent: "center",
            alignItems: "center",
    },
    circle3: {
            marginRight: -10,
            marginTop: 0,
            width: 40,
            height: 40,
            borderRadius: 20,
            backgroundColor: globalStyles.colors.buttonBlue1,
            marginBottom: 5,
            justifyContent: "center",
            alignItems: "center",
    },
    circle4: {
        marginRight: -20,
        marginTop: 10,
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: globalStyles.colors.buttonBlue1,
        marginBottom: 5,
        justifyContent: "center",
        alignItems: "center",
    },
    boxText: {
        marginTop: 40,
        color: globalStyles.colors.black,
        fontWeight: "bold",
    },
    titleContainer: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        marginBottom: 20,
        width: "100%",
    },
    title: {
        textAlign: "left",
        fontSize: 24,
        fontWeight: "bold",
    },
    liveButton: {
        paddingTop: 10,
        paddingBottom: 10,
        paddingHorizontal: 20,
        backgroundColor: globalStyles.colors.red,
        borderRadius: 5,
    },
    liveButtonText: {
        color: globalStyles.colors.white,
        fontWeight: "bold",
    },
    billIdAndStatus: {
        paddingHorizontal: 10,
        marginTop: -10,
        paddingBottom: 20,
    },
    id: {
        fontSize: 20,
        fontWeight: "bold",
        paddingBottom: 20,
    },
    statusBox: {
        paddingHorizontal: 10,
        width: 100,
        height: 25,
        borderRadius: 15,
        backgroundColor: globalStyles.colors.orange,
        marginBottom: 5,
        shadowColor: globalStyles.colors.black,
        shadowOffset: {width: 0, height: 2},
        shadowOpacity: 0.3,
        shadowRadius: 4,
    },
    bookmarkOutline: {
        position: "absolute",
        left: 3,

    },
    shadedBookmark: {
        position: "absolute",
        zIndex: 1,
        top: 2.5,
        left: 3,
    },
    simplifyButton: {
        position: "absolute",
        bottom: 25,
        right: 20,
        backgroundColor: globalStyles.colors.buttonBlue1,
        paddingTop: 10,
        paddingBottom: 10,
        paddingHorizontal: 15,
        borderRadius: 20,
    },
    simplifyButtonText: {
       color: globalStyles.colors.darkBlue,
       fontWeight: "bold",
    },
    modalOverlay: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: 'rgba(0,0,0,0.5)',
    },
    modalContainer: {
        marginTop: height/8,
        marginLeft: -width/10,
        width: '65%',
        padding: 20,
        backgroundColor: globalStyles.colors.white,
        borderRadius: 10,
        alignItems: 'stretch',
    },
    item: {
        fontSize: 18,
        padding: 10,
        textAlign: 'left',
    },
    divider: {
        height: 1,
        backgroundColor: '#dcdcdc',
        marginHorizontal: 20,
    },
    simplifiedBar: {
        marginTop: 30,
        padding: 10,
        backgroundColor: globalStyles.colors.white,
        borderRadius: 10,
        alignItems: "center",
        justifyContent: "center",
    },
    sliderLabels: {
        flexDirection: "row",
        justifyContent: "space-between",
        width: 250,
        marginTop: 5,
    },
    label: {
        fontSize: 14,
        color: "#666",
    },
    activeLabel: {
        fontSize: 14,
        fontWeight: "bold",
        color: globalStyles.colors.black,
    },
    // Expert's Thoughts Section
    expertTitle: {
        fontFamily: 'Montserrat_400Regular',
        width: "83%",
        marginTop: 30,
        fontSize: 26,
        fontWeight: "bold",
        color: globalStyles.colors.black,
    },
    expertDescription: {
        fontFamily: 'Montserrat_400Regular',
        marginTop: 10,
        fontSize: 14,
        color: globalStyles.colors.black,
    },
    dropDown: {
        marginTop: 30,
        width: "80%",
        height: 50,
        flexDirection: "row",
        alignItems: "center",
        paddingHorizontal: 20,
        elevation: 2,

        backgroundColor: globalStyles.colors.white,
        borderRadius: 10,
        boxShadow: '0px 4px 4px rgba(0, 0, 0, 0.25)',
    },
    dropDownHeaderText: {
        fontFamily: 'Montserrat_400Regular',
        fontSize: 17,
        color: globalStyles.colors.black,
    },
    dropdownContent: {
        width: "80%",
        borderBottomLeftRadius: 10,
        borderBottomRightRadius: 10,
        boxShadow: '0px 4px 4px rgba(0, 0, 0, 0.25)',
        backgroundColor: globalStyles.colors.white,
        padding: 14,
    },
    infoText: {
        fontFamily: 'Montserrat_400Regular',
        fontSize: 14,
        color: globalStyles.colors.black,
    },
});

export default styles;